.PHONY:lab4-1 lab4-2 lab4-3 lab4-4 ex4-1 ex4-2 ex4-3 

lab4-1:
	g++ lab4-1.cpp -o lab4-1
	./lab4-1

lab4-2:
	g++ lab4-2.cpp -o lab4-2
	./lab4-2

lab4-3:
	g++ lab4-3.cpp -o lab4-3
	./lab4-3

lab4-4:
	g++ lab4-4.cpp -o lab4-4
	./lab4-4

ex4-1:
	g++ ex4-1.cpp -o ex4-1
	./ex4-1

ex4-2: 
	g++ ex4-2.cpp -o ex4-2 
	./ex4-2

ex4-3:
	g++ ex4-3.cpp -o ex4-3
	./ex4-3